INSERT INTO T_ALUMNO(C_ALUMNO_NOMBRE, C_ALUMNO_GRUPO) VALUES('Rafael','2DAM');
INSERT INTO T_PRACTICA(C_TITULO_PRACTICA, C_DIFICULTAD_PRACTICA) VALUES('Proyecto Intermodular',10);
INSERT INTO ALUMNO_PRACTICA(ALUMNO_C_ALUMNO_MATRICULA, PRACTICA_C_CODIGO_PRACTICA, FECHA, NOTA) VALUES(1,1,'hoy',8);